[network_zenoh]
ca_cert = """
-----BEGIN CERTIFICATE-----\r
MIIBaTCCAQ6gAwIBAgIII1Y+LHfUDLQwCgYIKoZIzj0EAwIwHzEQMA4GA1UECgwH\r
Q0lUQUh1YjELMAkGA1UEAxMCQ0EwIBcNNzUwMTAxMDAwMDAwWhgPNDA5NjAxMDEw\r
MDAwMDBaMB8xEDAOBgNVBAoMB0NJVEFIdWIxCzAJBgNVBAMTAkNBMFkwEwYHKoZI\r
zj0CAQYIKoZIzj0DAQcDQgAEm2nEkL+4OSfqCTrbxolaUmCihXyxbU1yR4pZkgno\r
s+TPERSl8FrTDjbBfUBmslxhZ1H6Q6EnW3hqc7st863SfqMyMDAwHQYDVR0OBBYE\r
FLQM1HcsPlYj5wYFPx6Ku3wszdRAMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0E\r
AwIDSQAwRgIhAIYtXmvQ1vxHNuPXO0yygWv468SgBxNIsYw25YiwdUKkAiEA8LuM\r
EQY1CH73vs2wqRN3lsy2efmK9+1D0NgwUEcjxAM=\r
-----END CERTIFICATE-----\r
"""
cert = """
-----BEGIN CERTIFICATE-----\r
MIIBWzCCAQGgAwIBAgIIIqXQCkqeMBIwCgYIKoZIzj0EAwIwHzEQMA4GA1UECgwH\r
Q0lUQUh1YjELMAkGA1UEAxMCQ0EwIBcNNzUwMTAxMDAwMDAwWhgPNDA5NjAxMDEw\r
MDAwMDBaMCkxEDAOBgNVBAoMB0NJVEFIdWIxFTATBgNVBAMTDHRlc3QtY2hhaW4t\r
MDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEdKFRY6yebPGnf3wCFNpaOET/aF\r
/w/ffT4v/sekYWlUf1kL1y8DAddqUhRWsxo62ZssCW1K5YrDnFGj6Ldtb2SjGzAZ\r
MBcGA1UdEQQQMA6CDHRlc3QtY2hhaW4tMDAKBggqhkjOPQQDAgNIADBFAiEAiG15\r
sHOefkVWdAHBijUFot26CXip6pzGn5ISh0KHpMICIFA+oGBjV0KoIYrIUA4eSUlT\r
AqJz7l68WOnQmCmTAZLo\r
-----END CERTIFICATE-----\r
"""
chain_id = '63586a3c0255f337c77a777ff54f0040b8c388da04f23ecee6bfd4953a6512b4'
domain = 'test-chain-0'
enable_metrics = true
grpc_port = 50000
metrics_port = 60000
node_address = 'example/node_address'
port = 40000
priv_key = """
-----BEGIN PRIVATE KEY-----\r
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgerheIx0KhihGyB5G\r
pQXNNJXfhAQG29kMfqG8Phd0cVWhRANCAARHShUWOsnmzxp398AhTaWjhE/2hf8P\r
330+L/7HpGFpVH9ZC9cvAwHXalIUVrMaOtmbLAltSuWKw5xRo+i3bW9k\r
-----END PRIVATE KEY-----\r
"""
protocol = 'quic'
validator_address = 'example/validator_address'

[[network_zenoh.peers]]
domain = 'test-chain-node1'
protocol = 'quic'
port = 40001

[[network_zenoh.peers]]
domain = 'test-chain-node2'
protocol = 'quic'
port = 40002

[[network_zenoh.peers]]
domain = 'test-chain-node3'
protocol = 'quic'
port = 40003

[[network_zenoh.modules]]
module_name = 'consensus'
hostname = '127.0.0.1'
port = 50001

[[network_zenoh.modules]]
module_name = 'executor'
hostname = '127.0.0.1'
port = 50002

[[network_zenoh.modules]]
module_name = 'storage'
hostname = '127.0.0.1'
port = 50003

[[network_zenoh.modules]]
module_name = 'controller'
hostname = '127.0.0.1'
port = 50004

[[network_zenoh.modules]]
module_name = 'crypto'
hostname = '127.0.0.1'
port = 50005
